### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by GitHub-TXZ** [nihaomiao/MICCAI22_ADN#6]
“Yes, as mentioned in our paper, "after skull stripping, we resample all NCCTs to be 1.2 × 1.2 × 5 mm^3 and reshape
them to be 256×256×40 using the Python package nilearn."

“I think it is unreasonable to reshape the image to 40256256 after resampling. You should use the original volume to calculate the relevant metrics, because the asymmetry after resampling cannot represent the asymmetry of the original image.”

**Comment by nihaomiao** [comment]
Hi, @GitHub-TXZ, I agree that after resampling, the position of the original stroke lesion region will change. But since we conduct all experiments on the resampled dataset, the metrics will be computed on resampled stroke regions. So I think it is OK. One can simply regard the resampled dataset as a new dataset, independent of the original one.

**Comment by GitHub-TXZ** [comment]
“Okay, thank you very much. I have two more questions: 1) Can you provide three pre-trained models? I have already sent an email to your mailbox, but you may not have seen it. 2) How did you reproduce the SEAN paper?

**Comment by yimuu** [comment]
The Dice presented in SEAN (Symmetry-Enhanced Attention Network for Acute Ischemic Infarct Segmentation with Non–Contrast CT Images) is 0.5784, but in your paper is 0.5047. Since SEAN dose not publish the source code, how do you reproduce SEAN?

**Comment by nihaomiao** [comment]
HI, @GitHub-TXZ, sorry to hear about that. Recently I am too busy to check my Gmail. The pre-trained model links are: https://drive.google.com/drive/folders/198JNeouZdOLo__wVe30KXaiS1ScwaOTn?usp=drive_link
These checkpoints should provide good initialization but note that the pre-processing (skull-striping and denoising) is performed by doctors using some private GUI programs (mainly written by MATLAB). It may be hard for me to access these original pre-processing programs. 

For the SEAN paper, we implement it based on the details given in their paper. We run the program in our resampled dataset, which is different from the original dataset. The lower score of SEAN may be because 1. our implementation is not perfect; 2. resampled dataset is harder. 

Please feel free to let me know if you have more questions!
